name: Deploy site

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 17.x
    - name: Build
      run: yarn install
    - name: Deploy to actions
      uses: JamesIves/github-pages-deploy-action@4.1.8
      with:
        branch: gh-pages
        folder: dist
